### ISSUE TITLE
Including custom linters

### ISSUE THREAD

**Issue by kubawolanin** [lesshint/gulp-lesshint#11]
Hello!
Since `2.0.0` lesshint allows you to [create your custom linters](https://github.com/lesshint/lesshint#custom-linters). Is there a way to do that in gulp-lesshint as well?

Thank you!

**Comment by garethwhittaker** [comment]
Hi @kubawolanin,

I believe you can include custom linters within your `.lesshintrc` file:

```
"linters": [
    "./plugins/linters/sampleLinter",
    require("./plugins/linters/otherSampleLinter")
]
```

**Comment by kubawolanin** [comment]
Thank you @garethwhittaker! I should have read the docs more carefully.
I'm closing this issue then. 

Thanks again! :)
