### ISSUE TITLE
Add a fail reporter

### ISSUE THREAD

**Issue by jwilsson** [lesshint/gulp-lesshint#13]
We should add a fail reporter that can be used to fail the build if there are linting errors.

**Comment by santiph** [comment]
+1

**Comment by DamienCassou** [comment]
Yes please, this is a bit annoying :-). Or maybe just some workaround documentation?

**Comment by DamienCassou** [comment]
Here is a workaround:

``` js
        .pipe(gulpif(
            function(file) {
                return !file.lesshint.success;
            },
            gulpfail('Failed to lint less files', true)));
```

This requires gulp-if and gulp-fail.

**Comment by jwilsson** [comment]
Thanks for the workaround @DamienCassou.

I do however have a proposed method addition up in #14, let me know what you guys think!
