### ISSUE TITLE
Multiple Less Files

### ISSUE THREAD

**Issue by Antonvanzyl** [lesshint/gulp-lesshint#15]
Hi

When I use gulp-lesshint on my less files it ignores my properties I have set. If I reduce the number of less files I add to the gulp.src, around 3, everything works perfectly and my rules are applied, once I have 4 or more less files in the gulp.src then my rules are ignored.

Gulp Task: 
`
return gulp.src(
// Gather all the less files
 [
   path.join(config.paths.src.styles, '**/*.less'),
])
//Validate the less
.pipe(lesshint())
//Report on any issues
.pipe(lesshint.reporter());
`

.lesshintrc file
'{
    "fileExtensions": [".less"],
    "qualifyingElement":{
        "enabled":false
    },
    "zeroUnit": {
        "enabled": false
    },
    "propertyOrdering": {
        "enabled": false
    },
    "importantRule": {
        "enabled": false
    },
    "finalNewline": {
        "enabled": false
    }
}'

**Comment by jwilsson** [comment]
Hi!
That sounds really strange, `gulp-lesshint` doesn't care about the amount of files, it's just running though everything Gulp passes it. Everything work when I ran it with both 4 files and more.

Could you try running the main `lesshint` CLI on the files, e.g. `lesshint src/**/*.less` and see if that works. 

Thanks!

**Comment by Antonvanzyl** [comment]
I used lesshint CLI and it worked 100%, after this I tested the Gulp again and it worked. So I dont know if I had the wrong version or something, but the issue was clearly on my side. Thank you for the help.
