### ISSUE TITLE
failOnError() throws TypeError if "excludedFiles" present in lesshint config

### ISSUE THREAD

**Issue by JerkyTreats** [lesshint/gulp-lesshint#22]
Entry:
```
gulp.task('less-lint', function () {
  return gulp.src(lessFilesToWatch)
    .pipe(lesshint({ 
      configPath : lessConfig
    }))
    .pipe(lesshint.reporter())
    .pipe(lesshint.failOnError());
});
```

lessConfig definition:
```
{
  "excludedFiles": [
    "foo.less"
  ]
}
```

This combination throws:
```
.../node_modules/gulp-lesshint/index.js:91
        file.lesshint.results.forEach((result) => {
                     ^

TypeError: Cannot read property 'results' of undefined
```

Works correctly if failOnError() is not called. Tested in 2.1.0 and 3.0.0

**Comment by jwilsson** [comment]
Hmm, does `lessFilesToWatch` include/match the file(s) in `excludedFiles`?

**Comment by JerkyTreats** [comment]
Yeah, basically `foo/*.less`

As a workaround, I tried defining the excluded files in the gulp src, which works as expected. I'll just do this for now.

**Comment by trickydisco78** [comment]
I am having the same issues. I want to pattern match against everything in my assets folder
```
/assets/*.less
/assets/less/bootstrap/*.less
```

Everytime I state an array as gulp.src i get the same error as above. also if i pattern match like this:

```
`gulp.task('lesslint', () => {
    return gulp.src('app/assets/**/*.less')
    .pipe($.lesshint({
        configPath: './.lesshintrc'
        }))
    //.pipe(browserSync.stream())
    .pipe($.lesshint.reporter())
    .pipe($.lesshint.failOnError());
});`

```

**Comment by jwilsson** [comment]
Sorry guys, totally forgot about this one.

I'll have a new version out later today.

**Comment by trickydisco78** [comment]
Excellent. Cheers. I made that change locally and it fixed it. although it did throw and error if i had
  "borderZero": true in my lesshintrc file

**Comment by trickydisco78** [comment]
![image](https://cloud.githubusercontent.com/assets/3627429/25695050/7b472f96-30a9-11e7-850b-4e24aacea198.png)

**Comment by trickydisco78** [comment]
Ignore me. i'm being an idiot. True isn't a valid option
