### ISSUE TITLE
Update gulp-lesshint to include universalSelector linter

### ISSUE THREAD

**Issue by cian-w** [lesshint/gulp-lesshint#24]
Would it be possible get an update to include the option to enable or disable the universalSelector rule like in lesshint?

See the PR for lesshint: https://github.com/lesshint/lesshint/pull/336 

Thanks!

**Comment by jwilsson** [comment]
Clearing your `node_modules` folder should do it, since `gulp-lesshint` depends on `lesshint` `^3.0.0` :)

**Comment by cian-w** [comment]
Does that mean I have to change the universalSelector to false in the defaults.json in the lesshint package or can I access it somewhere in gulp-lesshint?

**Comment by jwilsson** [comment]
No, just set it to whichever value you want in your local `.lesshintrc` file and it'll pick it up.

**Comment by cian-w** [comment]
Excellent that worked. Thank you!
