### ISSUE TITLE
failOnError() doesn't fail the task

### ISSUE THREAD

**Issue by slamflipstrom** [lesshint/gulp-lesshint#28]
Thanks for all the great work on this library!

We've recently run into an issue where `failOnError()` isn't failing the task like we expect it to. Can others confirm this same behavior?

```
module.exports = (src, config) => {
  let stream = gulp.src(src)
    .pipe(lessHint({}))
    .pipe(lessHint.reporter())
    .pipe(lessHint.failOnError())
    .pipe(config.debug());
  
  return stream
};
```

**Comment by jwilsson** [comment]
Hi!
That sounds strange, I'm getting the expected result when I run it. 

Just to rule it out, though. Have you configured the `severity` as `error`? It'll only fail the build if there are errors, not for warnings (slight difference from the main `lesshint` which exits with `1` even on warnings).

I'm guessing you've tried without `config.debug()` too? Or could that swallow the error somehow?

**Comment by slamflipstrom** [comment]
Thanks for the prompt response. 

I double checked and the severity for all rules are set to `error`. I've also experimented with `config.debug()` like you mentioned and I still receive the same result. The error appears in gulp's output but it doesn't fail the task.

![image](https://user-images.githubusercontent.com/8062052/26992807-8cbc0ef0-4d1d-11e7-8c33-da5b2e1805bf.png)

**Comment by jwilsson** [comment]
Hmm, do you have something else that could capture the error?

But by the look of your output, it's should have failed it. Does running `echo $?` after running `gulp` give you `1`? And does the Less files compile correctly?

**Comment by slamflipstrom** [comment]
From what I can tell the error isn't being captured elsewhere.

After a closer look, the task fails as expected when I remove `exlcludedFiles` in the .lesshintrc. I decided to try this out after noticing #22. 

Any idea why the task doesn't fail when `excludedFiles` is present in the .lesshintrc?

**Comment by jwilsson** [comment]
I have no idea, that shouldn't matter. It did help me find another bug though 😬 , but I don't think that's related to your problem.

I'm afraid I'm out of ideas. I guess you could work around it by adding a negate glob pattern in your `gulpfile.js` and don't use `excludedFiles`. Would that work?

**Comment by slamflipstrom** [comment]
The issue was due to some gulp amateurism on my part and not the library 😆. Thanks for being so responsive!

**Comment by jwilsson** [comment]
Great, glad we got it sorted out! 😄
