### ISSUE TITLE
Enhancement: group logs together

### ISSUE THREAD

**Issue by adam-lynch** [lesshint/gulp-lesshint#4]
We've a lot going on with gulp and it's hard to see lesshint warnings & errors. CoffeeLint groups them together (if CoffeeLint is the one I'm thinking of)

**Comment by jwilsson** [comment]
Sounds really useful and like a great candidate for a new reporter. @adam-lynch feel like submitting a PR for it?

**Comment by adam-lynch** [comment]
@jwilsson will give it a go soon

**Comment by jwilsson** [comment]
@adam-lynch I don't know if you saw our discussion in https://github.com/lesshint/lesshint/pull/146 but we're gonna move away from keeping reporters in the main projects. 

But please work on it and publish it to npm for later usage with the main lesshint package and other plugins :)
