### ISSUE TITLE
Error: Cannot find module './utils'

### ISSUE THREAD

**Issue by rejas** [lesshint/gulp-lesshint#43]
Hi, with version 5.0.1 I get the error from the title. 

Seems that utils.js is  not included in the npm installation (only index.js is listed in the package.json)

**Comment by jwilsson** [comment]
Oh! Sorry about that and thanks for the investigation! I'll get a new release out immediately.

**Comment by jwilsson** [comment]
This is fixed in `5.0.2`.

**Comment by rejas** [comment]
Fix confirmed :-) Thx for the quick response.
