### ISSUE TITLE
How to access file object

### ISSUE THREAD

**Issue by simoneldevig** [lesshint/gulp-lesshint#49]
Hi,

I would like my production build to fail on warnings and I would therefore like to access the file object in order to show what the errors are but I can figure out how to access it.

Here is the current setup:
```
gulp.task('lesslint', () => {
  return gulp.src(PATHS)
    // Run LESS hint
    .pipe(gulpif(isProduction(),
      lesshint({
        configPath: './.lesshint.json',
        maxWarnings: -1
      })
      .on('error', err => {
        log(colors.bgRed.white(err.message));
        // Tell TeamCity an error occured
        teamcity.error(err);
        // Quit process to fail build
        if (isProduction()) process.abort();
      })
    ))
    .pipe(gulpif(isProduction, lesshint.failOnError()))
    .pipe(gulpif(isProduction(), lesshint.reporter()))
});
```

Where shoud I calll `file.lesshint.results` in order to not get undefined? :)

**Comment by jwilsson** [comment]
Hi!
You could use something like [gulp-tap](https://www.npmjs.com/package/gulp-tap), for example:

```js
gulp.task('lesslint', () => {
  return gulp.src(PATHS)
    .pipe(lesshint())
    .pipe(tap(file) => {
        console.log(file.lesshint)
    }));
    // Do some other things ...
});
```

**Comment by simoneldevig** [comment]
Thanks @jwilsson - I will give it a go :)

**Comment by simoneldevig** [comment]
@jwilsson - I get undefined for `file.lesshint` - any ideas?

**Comment by jwilsson** [comment]
@simoneldevig Strange, how does your code look now?

**Comment by simoneldevig** [comment]
@jwilsson - switching to map-stream resolved the issue.

Thx for the help :)
