### ISSUE TITLE
Handling of custom reporters

### ISSUE THREAD

**Issue by patrickmarabeas** [lesshint/gulp-lesshint#7]
Unless I'm being a spud and completely missing how this is handled, the following doesn't do anything when passed a custom reporter:

```
lesshintPlugin.reporter = function (reporter) {
    var lesshint = new Lesshint();

    if (reporter) {
        reporter = lesshint.getReporter( /* what reporter!? */ );
    } else {
        reporter = require('lesshint-reporter-stylish');
    }

    /* . . . */

};
```

Currently resolving the problem by rolling my own `reporter` function:

```
var myReporter = require('./reporters/myReporter.js');

/* . . . */

var lesshintReporter = function(reporter) {
    if (!reporter) {
        reporter = require('lesshint-reporter-stylish');
    }

   /* . . . */

};

/* . . . */

gulp.task('lesshint', function() {
    return gulp.src('...')
        .pipe(lesshint())
        .pipe(lesshintReporter(myReporter)));
```

Worth reviewing the docs and/or fixing with your intended implementation (passing name vs giving it the reporter module as I have done).

**Comment by jwilsson** [comment]
Sorry about the confusion!

The docs are for `2.0` which isn't released yet due to some upstream delays. I'll add a link to the `1.x` docs.

**Comment by patrickmarabeas** [comment]
We are using `2.0.0-rc`. Issue still stands. If you define a reporter, it isn't actually used by `lesshint`.

**gulp-lesshint/index.js**

```
lesshintPlugin.reporter = function (reporter) {
    var lesshint = new Lesshint();

    if (reporter) {
        reporter = lesshint.getReporter();
```

**lesshint/lib/lesshint.js**

```
Lesshint.prototype.getReporter = function (reporter) {
    var reporterPath;

    // Nothing defined, just fall back to our simple default
    if (!reporter) {
        reporterPath = path.resolve(__dirname, './reporters/default');

        return require(reporterPath);
    }
```

Supplying no reporter uses `lesshint-reporter-stylish`, supplying a reporter uses `default`.

**Comment by jwilsson** [comment]
Ah, jeez. Sorry about that, I'll fix it.
