### ISSUE TITLE
Reporter should process complete results

### ISSUE THREAD

**Issue by patrickmarabeas** [lesshint/gulp-lesshint#8]
The reporter is being called against each file with errors, rather than being given an object of all issues.
- When running sequentially with other tasks the results get scattered
- Can only format on a per file basis
- Unable to report totals / single line condensed output with a custom reporter
- Unable to do fancy table reports
- Can't log results to a file simply

**Comment by jwilsson** [comment]
Pull requests are always welcome :)

**Comment by patrickmarabeas** [comment]
I'll add it to the list

**Comment by jwilsson** [comment]
@patrickmarabeas Just wanted to check in on how it's going?
