### ISSUE TITLE
Adding the absolute file path to results.

### ISSUE THREAD

**Issue by garethwhittaker** [lesshint/gulp-lesshint#9]
The relative file path is currently passed through to the linter here:

https://github.com/lesshint/gulp-lesshint/blob/master/index.js - line 41
`results = lesshint.checkString(contents, file.relative);`

whilst the absolute file path would be useful for my reporter. Could this be a config option or an extra property made available within results if this line was amended to:

`results = lesshint.checkString(contents, file.path);`

Always happy to contribute with a PR if there's a consensus on including this and how.

**Comment by jwilsson** [comment]
Makes sense, since we're gonna return the relative path in each result object anyway.

PR for your second suggestion welcome!

**Comment by garethwhittaker** [comment]
The results array currently uses this second param to populate `result.fullPath` (https://github.com/lesshint/lesshint/blob/master/lib/linter.js#L182) so there are knock-on effects for those who want to use the relative path with this approach. Other than a config option, is there another suitable solution that would work for both?

**Comment by jwilsson** [comment]
I think it's OK to introduce this breaking change since we'll tag `2.0` soon and each reporter can choose to handle this the way the see fit (using the full path or retrieving the relative once themselves based on the full path).
